# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69087877381cf6517bfc4182fd970c3cd4c1710e143c9cc68f7e81a04962c9f266b963dd4158f3658842cbc9dd6f0fe167f2cb696a6053a4a14a2e257326e5d9

test:
  secret_key_base: 4f5cb95c012c7c51c1c8b8519fc74796ae6662aad026924c49244a2c25edd092f57bf218b6077eaaf452a2b0680e0cb3c17550c73b24fdb830e23199e153f97f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
